server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: campus-platform
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.148.245.72:3306/campus_system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: ldx18933875010
  data:
    redis:
      host: 8.148.245.72
      port: 6379
      database: 0
      password: ldx18933875010

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.campus.system.modules.*.entity
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

sa-token:
  token-name: Authorization
  timeout: -1
  active-timeout: 7200
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      uri: redis://:ldx18933875010@8.148.245.72:6379/

campus:
  upload-path: ./uploads